name: arXiv Paper Updater

on:
  schedule:
    - cron: '42 10 * * *'  # 每天 UTC 时间 16:30 运行（北京时间次日00:30）
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install arxiv
          pip install tenacity

      - name: Run arXiv Updater
        run: python arxiv_updater.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: Auto-update arXiv papers'
          branch: main
          file_pattern: README.md,article.json, arxiv_updater.py  # 确保相关文件被提交
